tasks/urls.py
from django.urls import path

from . import views

app_name = "tasks"

urlpatterns = [
    path("", views.TaskListView.as_view(), name="index"),
    path("add_task/", views.CreateTaskView.as_view(), name="add_task"),
    path("<int:pk>/update/", views.UpdateTaskView.as_view(), name="update_task"),
    path("<int:pk>/delete/", views.DeleteTaskView.as_view(), name="delete_task"),
]

todo/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("tasks.urls")),
]

tasks/models.py
from django.urls import reverse
from django.db import models


class Task(models.Model):
    task_name = models.CharField(max_length=255)
    task_complete = models.BooleanField(default=False)
    date_task_added = models.DateTimeField(auto_now_add=True)
    date_task_completed = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.task_name

    class Meta:
        ordering = ["date_task_added"]

    def get_absolute_url(self):
        return reverse("tasks:index")

tasks/forms.py
from django import forms

from .models import Task


class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ["task_name"]

tasks/views.py
from django.urls import reverse_lazy
from django.views.generic import ListView, RedirectView
from django.views.generic.edit import CreateView, DeleteView, UpdateView

from .models import Task


class TaskListView(ListView):
    model = Task
    template_name = "tasks/index.html"
    context_object_name = "tasks"
    ordering = ["date_task_added"]


class CreateTaskView(CreateView):
    model = Task
    fields = ["task_name"]


class UpdateTaskView(UpdateView):
    model = Task
    fields = ["task_name", "task_complete"]


class DeleteTaskView(DeleteView):
    model = Task
    success_url = reverse_lazy("tasks:index")

tasks/templates/tasks/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/water.css@2/out/water.css">
</head>

<body>

    {% block content %}
    {% endblock %}

</body>

</html>

tasks/templates/tasks/index.html
{% extends "tasks/base.html" %}
{% block title %}Task List{% endblock %}
{% block content %}
    <h1>Task List</h1>

    <ul>
        {% for task in tasks %}
        <li>{% if task.task_complete %}<s>{{ task.task_name }}</s> - <a href="{{ task.pk }}/update">&check;</a>{% else %}{{ task.task_name }} - <a href="{{ task.pk }}/update">Edit</a> | <a href="{{ task.pk }}/delete">Delete</a>{% endif %}</li>
        {% empty %}
        <li>No tasks available.</li>
        {% endfor %}<br>
        <li><a href="{% url 'tasks:add_task' %}">Add new task.</a></li>
    </ul>
{% endblock %}

tasks/templates/tasks/task_confirm_delete.html
{% extends "tasks/base.html" %}
{% block title %}Task Delete{% endblock %}
{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        <p>Are you sure you want to delete "{{ object }}"?</p>
        <input type="submit" value="Confirm" />
    </form>
{% endblock %}

tasks/templates/tasks/task_form.html
{% extends "tasks/base.html" %}
{% block title %}Task Add{% endblock %}
{% block content %}
    <h1>Task Form</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Add" />
    </form>
{% endblock %}